name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  larastan:
    name: Run Larastan
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, gd, pdo, openssl, curl, fileinfo,  intl
          tools: composer

      - name: Install Dependencies
        run: composer install --no-interaction --no-scripts --no-progress

      - name: Run Larastan
        run: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=1G
